# Generated by Django 4.2.7 on 2025-11-26 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kategori Obat',
                'verbose_name_plural': 'Kategori Obat',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_supplier', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='TransaksiPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Transaksi Penjualan',
                'verbose_name_plural': 'Transaksi Penjualan',
            },
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=150)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stok', models.PositiveIntegerField()),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obat', to='meditrack.kategoriobat')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obat_supplier', to='meditrack.supplier')),
            ],
            options={
                'verbose_name': 'Obat',
                'verbose_name_plural': 'Obat',
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_transaksi', to='meditrack.obat')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='meditrack.transaksipenjualan')),
            ],
            options={
                'verbose_name': 'Detail Transaksi',
                'verbose_name_plural': 'Detail Transaksi',
            },
        ),
    ]
