# Generated by Django 4.2.7 on 2026-01-29 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meditrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaksipenjualan',
            options={},
        ),
        migrations.AddField(
            model_name='transaksipenjualan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Keranjang (Draft)'), ('PENDING', 'Menunggu Pembayaran'), ('PAID', 'Lunas'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='transaksipenjualan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_penjualan', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
