# Generated by Django 4.2.7 on 2026-09-05 16:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def validate_existing_inventory(apps, schema_editor):
    alias = schema_editor.connection.alias
    invalid_items = apps.get_model('meditrack', 'DetailTransaksi').objects.using(alias).filter(jumlah__lte=0).exists()
    invalid_prices = apps.get_model('meditrack', 'Obat').objects.using(alias).filter(harga__lt=0).exists()
    if invalid_items or invalid_prices:
        raise RuntimeError('Migration stopped without changing data: correct legacy zero/negative quantities or negative prices, then retry migrate.')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meditrack', '0002_alter_transaksipenjualan_options_and_more'),
    ]

    operations = [
        migrations.RunPython(validate_existing_inventory, migrations.RunPython.noop),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('IN', 'Restock'), ('SALE', 'Penjualan'), ('ADJUSTMENT', 'Penyesuaian'), ('RETURN', 'Pengembalian')], max_length=12)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_before', models.PositiveIntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='obat',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obat',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='jumlah',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detailtransaksi',
            name='obat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_transaksi', to='meditrack.obat'),
        ),
        migrations.AlterField(
            model_name='obat',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='obat',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obat', to='meditrack.kategoriobat'),
        ),
        migrations.AlterField(
            model_name='obat',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obat_supplier', to='meditrack.supplier'),
        ),
        migrations.AddConstraint(
            model_name='detailtransaksi',
            constraint=models.CheckConstraint(check=models.Q(('jumlah__gt', 0)), name='detail_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='obat',
            constraint=models.CheckConstraint(check=models.Q(('harga__gte', 0)), name='obat_nonnegative_price'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='obat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='meditrack.obat'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='movement_positive_quantity'),
        ),
    ]
